README.md, lib/mihari/analyzers/base.rb, lib/mihari/analyzers/basic.rb, lib/mihari/cli.rb, lib/mihari/notifiers/the_hive.rb, lib/mihari/the_hive.rb, spec/analyzers/basic_spec.rb
Add taggning capability to the alert creation
=> feat: add tagging capability

lib/mihari/version.rb
Hotfix for the permission issue
=> v0.4.2 [skip travis]

lib/mihari/analyzers/base.rb, lib/mihari/emitters/the_hive.rb, spec/emitters/the_hive_spec.rb
Make ensure to save items as cache after emitting them to TheHive
=> refactor: change caching behavior

docker/Dockerfile
Update Dockerfile to reduce image size
=> chore: update Dockerfile

lib/mihari/analyzers/censys.rb
Remove useless argument check & simplify iteration
=> refactor: refactor Censys analyzer

lib/mihari/emitters/slack.rb, lib/mihari/notifiers/slack.rb, spec/emitters/slack_spec.rb
=> refactor: renew Slack notification format

lib/mihari/analyzers/censys.rb, lib/mihari/cli.rb, spec/analyzers/censys_spec.rb, spec/fixtures/vcr_cassettes/Mihari_Analyzers_Censys/when_given_certificates_type/_artifacts/1_5_1_1.yml, spec/fixtures/vcr_cassettes/Mihari_Analyzers_Censys/when_given_websites_type/_artifacts/1_6_1_1.yml
Add Censys websites & certificates lookup capabilities
=> feat: add Censys websites & certificates lookup

lib/mihari.rb, lib/mihari/analyzers/base.rb, lib/mihari/emitters/base.rb, lib/mihari/retriable.rb, spec/analyzers/analyzer_spec.rb, spec/retriable_spec.rb
Make enable to do a retry when Timeout::Error happens during the processing
=> feat: add retry feature

lib/mihari/analyzers/base.rb
Make emitter selection before starting parallel emission
=> refactor: add #valid_emitters method

lib/mihari/analyzers/base.rb, lib/mihari/emitters/base.rb, lib/mihari/retriable.rb, spec/retriable_spec.rb
Change to catch connection errors for retrying
=> refactor: improve retry-on-error

lib/mihari/cli.rb
=> Cli refactoring

README.md, lib/mihari/analyzers/passive_dns.rb, spec/analyzers/passive_dns_spec.rb
Add Pulsedive to passive_dns cross search
=> feat: update passive_dns command

lib/mihari/analyzers/dnstwister.rb, spec/analyzers/dnstwister_spec.rb
Change to return domains which have A record
=> fix: fix an issue in dnstwister lookup

lib/mihari.rb, lib/mihari/cli.rb, lib/mihari/config.rb, spec/config_spec.rb, spec/fixtures/test.yml
Make enable to load condiguration from a YAML file
=> feat: add YAML configuration option

lib/mihari/analyzers/circl.rb, lib/mihari/analyzers/dnpedia.rb, lib/mihari/analyzers/dnstwister.rb, lib/mihari/analyzers/passivetotal.rb, lib/mihari/analyzers/pulsedive.rb, lib/mihari/analyzers/securitytrails.rb, lib/mihari/analyzers/securitytrails_domain_feed.rb, lib/mihari/analyzers/shodan.rb, lib/mihari/analyzers/urlscan.rb, lib/mihari/analyzers/virustotal.rb
Change to raise an error when someting goes wrong because it is good to know an error
=> refactor: let it crash

lib/mihari/cli.rb
Make clear that "--limit" is a string
=> fix: fix Thor warning

lib/mihari/analyzers/crtsh.rb, lib/mihari/cli.rb, mihari.gemspec, spec/fixtures/vcr_cassettes/Mihari_Analyzers_Crtsh/_artifacts/1_3_1.yml
Make enable to specify excluding expired certificate or not
=> feat: revamp Crt.sh analyzer

lib/mihari/type_checker.rb
Do not validate email strictly for convinience
=> fix: check syntax only

lib/mihari/the_hive.rb, spec/analyzers/circl_spec.rb, spec/analyzers/pulsedive_spec.rb, spec/analyzers/virustotal_spec.rb, spec/emitters/slack_spec.rb, spec/emitters/the_hive_spec.rb, spec/fixtures/vcr_cassettes/Mihari_Emitters_TheHive/_valid_/1_1_1.yml
Mock Mihari.config insted of ENV
=> fix: fix config related issues

lib/mihari/cli.rb
Reload database settings after loading configuration from YAML to reflect the configuration
=> fix: fix error in configuration loading

lib/mihari/cli.rb, lib/mihari/database.rb
Add Database.connet to (re)connect to the database
=> refactor: add Database.connect

lib/mihari/alert_viewer.rb, lib/mihari/cli.rb, spec/alert_viewer_spec.rb, spec/spec_helper.rb, spec/support/shared_contexts/database_context.rb
Make possible to filter alerts by title, source and tag
=> feat: renew alerts command

spec/spec_helper.rb
More accurate CI env detection by checking default env variables of Travis CI
=> refactor: renew CI check

docker/Dockerfile
=> fix: fix package issues in Dockerfile

lib/mihari/version.rb
=> v1.2.1 [skip ci]

lib/mihari/analyzers/binaryedge.rb, lib/mihari/analyzers/shodan.rb, lib/mihari/errors.rb, lib/mihari/retriable.rb, spec/analyzers/binaryedge_spec.rb, spec/analyzers/shodan_spec.rb
Introduce RetryableError to catch a retryable error to make retries
=> feat: introduce RetryableError

lib/mihari/version.rb
=> v1.3.1 [skip ci]

lib/mihari/emitters/slack.rb, spec/emitters/slack_spec.rb
Add Shodan link in the Slack notification. (#188)
=> feat: add Shodan link (#188)

.github/workflows/test.yml, lib/mihari/database.rb, mihari.gemspec
=> feat: support MySQL

docker/Dockerfile
=> chore: update Dockerfile [skip ci]

lib/mihari/cli.rb, lib/mihari/config.rb
Add init_config command to create a (empty) config file (#213)
=> feat: add init_config command

lib/mihari/web/app.rb, mihari.gemspec
Show an instruction when the app is launched
=> chore: show an instruction for the app

lib/mihari/analyzers/base.rb, lib/mihari/cli.rb, lib/mihari/commands/config.rb, lib/mihari/commands/json.rb, lib/mihari/models/artifact.rb, lib/mihari/web/controllers/command_controller.rb, spec/cli_spec.rb, spec/models/artifact_spec.rb, spec/spec_helper.rb, spec/web/app_spec.rb
Add --ignore-old-artifacts option (#202)
=> feat: add --ignore-old-artifacts option

lib/mihari/analyzers/urlscan.rb, spec/analyzers/urlscan_spec.rb
=> feat: update urlscan.io analyzer

lib/mihari.rb, lib/mihari/cli/analyzer.rb, lib/mihari/cli/main.rb, lib/mihari/commands/search.rb, lib/mihari/commands/validate.rb, lib/mihari/mixins/rule.rb, spec/cli/main_spec.rb, spec/fixtures/rules/invalid_rule.yml, spec/fixtures/rules/valid_rule.yml, spec/schemas/rule_spec.rb
Add a command to validate a rule
=> feat: add validate command

lib/mihari/emitters/misp.rb
=> fix: return if artifacts are empty

lib/mihari/mixins/configuration.rb
Downcase config keys (for just in case)
=> refactor: downcase config keys

lib/mihari/analyzers/rule.rb
=> fix: remove unused constraint

lib/mihari/analyzers/rule.rb, lib/mihari/commands/search.rb, lib/mihari/schemas/rule.rb, lib/mihari/templates/rule.yml.erb, spec/analyzers/rule_spec.rb, spec/fixtures/vcr_cassettes/Mihari_Analyzers_Rule/shodan_ip_1_1_1_1.yml, spec/schemas/rule_spec.rb
=> feat: add disallowed_data_values option

lib/mihari.rb, lib/mihari/analyzers/rule.rb, lib/mihari/mixins/disallowed_data_value.rb, lib/mihari/schemas/rule.rb, lib/mihari/templates/rule.yml.erb, spec/analyzers/rule_spec.rb, spec/mixins/disallowed_data_value_spec.rb, spec/schemas/rule_spec.rb
Make possible to set a string as a disallowed data value
=> refactor: improve disallowed data value handling

lib/mihari/cli/analyzer.rb, lib/mihari/cli/base.rb, lib/mihari/commands/search.rb, lib/mihari/mixins/rule.rb, lib/mihari/schemas/rule.rb, lib/mihari/templates/rule.yml.erb, spec/schemas/rule_spec.rb
=> feat: make possible to set ignore-old-artifacts and ignore-threshold

lib/mihari/commands/init.rb
=> fix: include mixins right after module declaration

lib/mihari.rb, lib/mihari/analyzers/base.rb, lib/mihari/analyzers/censys.rb, lib/mihari/analyzers/shodan.rb, lib/mihari/database.rb, lib/mihari/models/alert.rb, lib/mihari/models/artifact.rb, lib/mihari/models/autonomous_system.rb, lib/mihari/models/geolocation.rb, lib/mihari/schemas/rule.rb, lib/mihari/serializers/alert.rb, lib/mihari/serializers/artifact.rb, lib/mihari/serializers/autonomous_system.rb, lib/mihari/serializers/geolocation.rb, lib/mihari/serializers/tag.rb, lib/mihari/structs/censys.rb, lib/mihari/structs/shodan.rb, lib/mihari/types.rb, lib/mihari/web/controllers/artifacts_controller.rb, mihari.gemspec, spec/analyzers/censys_spec.rb, spec/analyzers/shodan_spec.rb, spec/fixtures/vcr_cassettes/Mihari_Analyzers_Shodan/_artifacts/1_3_1.yml, spec/serializers/alert_spec.rb, spec/serializers/artifact_spec.rb, spec/serializers/tag_spec.rb
Add `autonomous_systems` and `geolocations` table to enrich IP address artifact. (#310)
=> Enrich IP address artifact

lib/mihari.rb, lib/mihari/analyzers/base.rb, lib/mihari/database.rb, lib/mihari/models/artifact.rb, lib/mihari/models/dns.rb, lib/mihari/models/whois.rb, lib/mihari/serializers/artifact.rb, lib/mihari/serializers/dns.rb, lib/mihari/serializers/whois.rb, lib/mihari/web/controllers/artifacts_controller.rb, mihari.gemspec, spec/analyzers/analyzer_spec.rb, spec/models/artifact_spec.rb, spec/models/dns_spec.rb, spec/models/whois_spec.rb
Add whois_records and dns_records table to enrich domain artifact (#310)
=> feat: enrich domain artifact

lib/mihari.rb, lib/mihari/models/autonomous_system.rb, lib/mihari/structs/ipinfo.rb, sig/lib/mihari/structs/ipinfo.rbs
=> fix: fix IPInfo related issue

lib/mihari/models/alert.rb, lib/mihari/web/controllers/alerts_controller.rb, sig/lib/mihari/models/alert.rbs, spec/models/alert_spec.rb, spec/support/shared_contexts/database_context.rb
Add asn, dns_record and reverse_dns_name filters
=> feat: upadte Alert search

lib/mihari.rb, lib/mihari/models/alert.rb, lib/mihari/structs/alert.rb, lib/mihari/types.rb, lib/mihari/web/controllers/alerts_controller.rb, sig/lib/mihari/models/alert.rbs, sig/lib/mihari/structs/alert.rbs, spec/models/alert_spec.rb
Wrap query params for Alert search by dry-struct
=> refactor: use dry-struct in Alert search

lib/mihari/commands/web.rb, lib/mihari/web/app.rb, sig/lib/mihari/web/app.rbs
Make possible to set Threads and Verbose options through CLI
=> feat: make Puma configurable

lib/mihari/errors.rb, lib/mihari/mixins/configuration.rb, spec/mixins/configuration_spec.rb
Check configuration file path before loading
=> refactor: check configuration file path

mihari.gemspec
=> fix: update dry-container

lib/mihari/analyzers/binaryedge.rb, lib/mihari/analyzers/censys.rb, lib/mihari/analyzers/onyphe.rb, lib/mihari/analyzers/rule.rb, lib/mihari/analyzers/shodan.rb, lib/mihari/analyzers/virustotal_intelligence.rb, lib/mihari/analyzers/zoomeye.rb, lib/mihari/cli/analyzer.rb, lib/mihari/schemas/rule.rb, sig/lib/mihari/analyzers/binaryedge.rbs, sig/lib/mihari/analyzers/censys.rbs, sig/lib/mihari/analyzers/onyphe.rbs, sig/lib/mihari/analyzers/shodan.rbs, sig/lib/mihari/analyzers/virustotal_intelligence.rbs, sig/lib/mihari/analyzers/zoomeye.rbs, spec/schemas/rule_spec.rb
=> feat: add throttling feature

lib/mihari.rb, lib/mihari/emitters/slack.rb, lib/mihari/enrichers/ipinfo.rb, lib/mihari/mixins/disallowed_data_value.rb, mihari.gemspec, sig/lib/mihari.rbs, sig/lib/mihari/emitters/slack.rbs, sig/lib/mihari/mixins/disallowed_data_value.rbs
Remove mem and use memist (#387)
=> refactor: remove mem

lib/mihari.rb, lib/mihari/enrichers/ipinfo.rb, lib/mihari/feed/reader.rb, lib/mihari/http.rb, lib/mihari/structs/ipinfo.rb, mihari.gemspec, sig/lib/mihari/feed/reader.rbs, sig/lib/mihari/http.rbs, spec/fixtures/vcr_cassettes/Mihari_HTTP/_post/with_application/json/1_1_2_1.yml, spec/fixtures/vcr_cassettes/Mihari_HTTP/_post/with_application/x-www-form-urlencoded/1_1_1_1.yml, spec/http_spec.rb
Remove http gem and use simple HTTP client instead of that
=> refactor: remove http gem

lib/mihari/structs/shodan.rb
Fix #424 by adding a dirty hack
=> fix: fix Shodan hostnames issue (#424)

lib/mihari/analyzers/base.rb, lib/mihari/analyzers/rule.rb, lib/mihari/errors.rb, lib/mihari/mixins/retriable.rb, spec/analyzers/analyzer_spec.rb, spec/analyzers/rule_spec.rb
- Add `ConfigurationError` 
- Add `on` option in `Mihari::Mixins::Retriable#retry_on_error`
=> Refactorings

lib/mihari.rb, lib/mihari/analyzers/rule.rb, lib/mihari/constants.rb, lib/mihari/schemas/rule.rb, lib/mihari/structs/rule.rb, lib/mihari/types.rb, sig/lib/mihari/constants.rbs, sig/lib/mihari/structs/rule.rbs, sig/lib/mihari/types.rbs, spec/schemas/rule_spec.rb
Make it possible to customize emitters via "emitters" option
=> feat: add emitters option

lib/mihari/commands/search.rb
Add a confirmation before overwriting a rule
=> feat: rule overwrite confrimation

lib/mihari/schemas/analyzer.rb, lib/mihari/schemas/emitter.rb, lib/mihari/types.rb
=> refactor: upcase http

lib/mihari/analyzers/rule.rb, lib/mihari/version.rb, spec/analyzers/rule_spec.rb
Fix wrong usage of Enumerable#any? & bump the version up
=> Fix disallowed data values error

lib/mihari.rb, lib/mihari/emitters/the_hive.rb, lib/mihari/schemas/emitter.rb, mihari.gemspec, sig/lib/mihari.rbs, sig/lib/mihari/emitters/the_hive.rbs, spec/emitters/the_hive_spec.rb
Support TheHive v5 along with v4.
=> Support TheHive v5

lib/mihari/web/app.rb
=> fix: rescue Launchy::CommandNotFoundError

lib/mihari/structs/virustotal_intelligence.rb, spec/analyzers/virustotal_intelligence_spec.rb, spec/fixtures/vcr_cassettes/Mihari_Analyzers_VirusTotalIntelligence/domain/_artifacts/1_3_1_1.yml, spec/fixtures/vcr_cassettes/Mihari_Analyzers_VirusTotalIntelligence/file/_artifacts/1_1_1_1.yml, spec/fixtures/vcr_cassettes/Mihari_Analyzers_VirusTotalIntelligence/ip/_artifacts/1_4_1_1.yml, spec/fixtures/vcr_cassettes/Mihari_Analyzers_VirusTotalIntelligence/url/_artifacts/1_2_1_1.yml
=> fix: fix VT intel URL search issue

lib/mihari/models/cpe.rb, lib/mihari/models/reverse_dns.rb
=> fix: fix NoMethodError while enriching artifact

lib/mihari/analyzers/rule.rb, lib/mihari/constants.rb, lib/mihari/models/artifact.rb, lib/mihari/schemas/enricher.rb, lib/mihari/schemas/rule.rb, lib/mihari/structs/rule.rb, lib/mihari/types.rb, spec/fixtures/vcr_cassettes/Mihari_Artifact/_enrich_by_enricher/with_Google_Public_DNS/1_7_3_1.yml, spec/models/artifact_spec.rb
Make possible to customize enrichers per rule.
=> feat: add enrichers in rule

lib/mihari/structs/rule.rb, lib/mihari/web/endpoints/rules.rb
Renew rule ID handling to make it simple.
=> refactor: renew rule ID handling

lib/mihari/models/geolocation.rb, lib/mihari/structs/ipinfo.rb, sig/lib/mihari/structs/ipinfo.rbs
=> fix: fix IPInfo enrichment issue (#492)

lib/mihari/errors.rb, lib/mihari/structs/rule.rb, lib/mihari/web/endpoints/rules.rb
Add `YAMLSyntaxError` class to handle YAML syntax related error
=> refactor: add YAMLSyntaxError class

.github/workflows/test.yml, lib/mihari/schemas/rule.rb
Make it possible to set Sigma like rule attributes. (add `references`, `related`, and `status`)
=> feat: add Sigma like rule attributes

lib/mihari/commands/search.rb
Stop throwing an error when catching RuleValidationError
=> refactor: improve error message output

lib/mihari/version.rb
- Remove Spyse supoprt (#510)
- Improve the error message output (#511)
=> v4.9.0 [skip ci]

lib/mihari.rb, lib/mihari/emitters/misp.rb, lib/mihari/emitters/the_hive.rb, lib/mihari/schemas/emitter.rb, sig/lib/mihari.rbs, sig/lib/mihari/emitters/misp.rbs, sig/lib/mihari/emitters/the_hive.rbs, spec/emitters/misp_spec.rb, spec/emitters/the_hive_spec.rb, spec/fixtures/vcr_cassettes/Mihari_Emitters_MISP/_emit/1_2_1.yml, spec/fixtures/vcr_cassettes/Mihari_Emitters_TheHive/_valid_/1_1_1.yml, spec/fixtures/vcr_cassettes/Mihari_TheHive/_valid_/1_1_1.yml, spec/fixtures/vcr_cassettes/Mihari_TheHive_Alert/_list/1_1_1.yml, spec/fixtures/vcr_cassettes/Mihari_TheHive_Artifact/_exists_/when_give_a_not_existing_value/1_1_1_1.yml, spec/fixtures/vcr_cassettes/Mihari_TheHive_Artifact/_exists_/when_give_an_existing_value/1_1_2_1.yml, spec/fixtures/vcr_cassettes/Mihari_TheHive_Artifact/_find_non_existing_artifacts/1_2_1.yml, spec/spec_helper.rb
Use `*_URL` instead of `*_API_ENDPOINT` to prevent misunderstanding like #513
=> refactor: use "_URL" instead of "_API_ENDPOINT"

lib/mihari/commands/web.rb, lib/mihari/web/app.rb
Update the default threads number for Puma.
=> refactor: update default threads value

spec/analyzers/pulsedive_spec.rb, spec/analyzers/securitytrails_spec.rb, spec/analyzers/virustotal_intelligence_spec.rb, spec/analyzers/virustotal_spec.rb, spec/analyzers/zoomeye_spec.rb, spec/emitters/slack_spec.rb
Use single subject as much as possible
=> refactor: use single subject

lib/mihari/entities/alert.rb, lib/mihari/entities/artifact.rb, lib/mihari/models/alert.rb
Stop loading artifact enrichments in alert search to improve performance
=> refactor: stop loading enrichments in search

lib/mihari/database.rb
Do not allow NULL in foreign keys
=> refactor: do not allow null in foreign keys

lib/mihari/web/endpoints/alerts.rb, lib/mihari/web/endpoints/rules.rb
=> fix: set correct success entity

lib/mihari.rb, lib/mihari/database.rb, spec/spec_helper.rb
Rename `DATABASE` (`database`) to `DATABASE_URL` (`database_url`)
=> refactor: use database url

lib/mihari/commands/initializer.rb, lib/mihari/structs/rule.rb, lib/mihari/templates/rule.yml.erb, lib/mihari/web/endpoints/rules.rb, spec/commands/initializer_spec.rb
Renew rule initialization methods
=> feat: renew rule initializaiton

lib/mihari/commands/initializer.rb, spec/commands/initializer_spec.rb
=> fix: fix issues in #420

lib/mihari/database.rb, lib/mihari/entities/alert.rb, lib/mihari/entities/artifact.rb, spec/web/endpoints/artifacts_spec.rb
Support bit int primary keys by stringfy those keys in API.
=> Support big int

lib/mihari/analyzers/base.rb, lib/mihari/commands/searcher.rb, lib/mihari/structs/rule.rb
Fix DB connection issue & change an option to overwrite an existing rule.
=> fix: fix DB connection issue

lib/mihari/analyzers/feed.rb, lib/mihari/emitters/webhook.rb, lib/mihari/feed/reader.rb, lib/mihari/http.rb, lib/mihari/schemas/analyzer.rb, spec/analyzers/feed_spec.rb, spec/http_spec.rb
=> refactor: renew HTTP & Feed

lib/mihari.rb, lib/mihari/analyzers/dnstwister.rb, lib/mihari/clients/dnstwister.rb, mihari.gemspec
=> chore: remove "dnstwister" gem

lib/mihari.rb, lib/mihari/analyzers/pulsedive.rb, lib/mihari/clients/publsedive.rb, mihari.gemspec
=> chore: remove "pulsedive" gem

lib/mihari.rb, lib/mihari/analyzers/binaryedge.rb, lib/mihari/clients/base.rb, lib/mihari/clients/binaryedge.rb, mihari.gemspec, spec/analyzers/binaryedge_spec.rb
=> refactor: remove "binaryedge" gem

lib/mihari/clients/crtsh.rb, lib/mihari/clients/dnstwister.rb, lib/mihari/clients/otx.rb, lib/mihari/clients/publsedive.rb
=> refactor: use Base#get

lib/mihari.rb, lib/mihari/analyzers/circl.rb, lib/mihari/clients/circl.rb, mihari.gemspec
=> refactor: remove CIRCL gem

lib/mihari.rb, lib/mihari/analyzers/greynoise.rb, lib/mihari/clients/greynoise.rb, mihari.gemspec
=> refactor: remove greynoise gem

lib/mihari.rb, lib/mihari/analyzers/virustotal.rb, lib/mihari/analyzers/virustotal_intelligence.rb, lib/mihari/clients/virustotal.rb, mihari.gemspec
=> refactor: remove VT gem

lib/mihari.rb, lib/mihari/commands/web.rb, lib/mihari/mixins/configurable.rb
Add `hide_config_values` setting for #590
=> feat: add hide_config_values setting (#590)

lib/mihari/schemas/rule.rb, lib/mihari/structs/rule.rb
Add `artifact_ttl` alias (alias for `artifact_lifetime`)
=> refactor: add artifact_ttl alias

lib/mihari/schemas/rule.rb, spec/schemas/rule_spec.rb
=> refactor: remove key_coercer

lib/mihari/analyzers/rule.rb, lib/mihari/emitters/base.rb, lib/mihari/emitters/database.rb, lib/mihari/emitters/misp.rb, lib/mihari/emitters/slack.rb, lib/mihari/emitters/the_hive.rb, lib/mihari/emitters/webhook.rb, lib/mihari/errors.rb, lib/mihari/structs/config.rb, spec/analyzers/rule_spec.rb, spec/emitters/database_spec.rb, spec/emitters/misp_spec.rb, spec/emitters/slack_spec.rb, spec/emitters/the_hive_spec.rb, spec/emitters/webhook_spec.rb, spec/support/shared_contexts/database_context.rb
Renew rule analyzer and emitters.
=> refactor: renew rule analyzer & emitters

lib/mihari/analyzers/censys.rb
Update Censys support (support both empty links and empty string cursors) (#600)
=> fix: update Censys support

lib/mihari/schemas/analyzer.rb, lib/mihari/schemas/rule.rb
Remove `Urlscan` schema and `dnpedia`
=> refactor: update analyzer schemas

lib/mihari/analyzers/base.rb, lib/mihari/analyzers/rule.rb, lib/mihari/commands/search.rb, lib/mihari/structs/rule.rb, spec/analyzers/rule_spec.rb
Revamp rule related classes to reduce the code complexity
=> Renew rule

lib/mihari.rb, lib/mihari/analyzers/rule.rb, lib/mihari/commands/rule.rb, lib/mihari/commands/search.rb, lib/mihari/emitters/base.rb, lib/mihari/emitters/misp.rb, lib/mihari/emitters/slack.rb, lib/mihari/emitters/the_hive.rb, lib/mihari/emitters/webhook.rb, lib/mihari/services/rule.rb, lib/mihari/web/endpoints/rules.rb, spec/analyzers/rule_spec.rb, spec/commands/rule_spec.rb, spec/emitters/database_spec.rb, spec/emitters/misp_spec.rb, spec/emitters/slack_spec.rb, spec/emitters/the_hive_spec.rb, spec/emitters/webhook_spec.rb, spec/services/rule_spec.rb, spec/support/shared_contexts/database_context.rb
Re-defining `Structs::Service` as a service class
=> refactor: add Rule service class

lib/mihari/analyzers/base.rb, lib/mihari/analyzers/binaryedge.rb, lib/mihari/analyzers/censys.rb, lib/mihari/analyzers/onyphe.rb, lib/mihari/analyzers/shodan.rb, lib/mihari/analyzers/urlscan.rb, lib/mihari/analyzers/virustotal_intelligence.rb, lib/mihari/analyzers/zoomeye.rb
Fix #666 by defining `Analyzer#sleep_interval` to ensure sleeping only if `interval` is not nil.
=> fix: fix #666

lib/mihari/analyzers/base.rb, lib/mihari/analyzers/binaryedge.rb, lib/mihari/analyzers/censys.rb, lib/mihari/analyzers/hunterhow.rb, lib/mihari/analyzers/onyphe.rb, lib/mihari/analyzers/shodan.rb, lib/mihari/analyzers/urlscan.rb, lib/mihari/analyzers/virustotal_intelligence.rb, lib/mihari/analyzers/zoomeye.rb, lib/mihari/config.rb, lib/mihari/constants.rb, lib/mihari/schemas/analyzer.rb
Introduce pagination limit option to prevent an issue like #664
=> feat: introduce pagination limit

frontend/src/swagger.yaml, lib/mihari/entities/artifact.rb, lib/mihari/models/alert.rb, lib/mihari/models/artifact.rb, lib/mihari/models/rule.rb, lib/mihari/structs/filters.rb, lib/mihari/web/endpoints/alerts.rb, lib/mihari/web/endpoints/artifacts.rb, lib/mihari/web/endpoints/rules.rb, spec/models/alert_spec.rb, spec/models/artifact_spec.rb, spec/models/rule_spec.rb
- Improve search queries
- Add a search feature for artifacts
- Fix cameCase vs. snake_case inconsistency
=> Renew search features

lib/mihari/structs/shodan.rb
Fix Shodan analyzer's geolocation issue (#883)
=> fix: fix Shodan geolocation issue (#883)

lib/mihari/services/builders.rb, spec/services/rule_builder_spec.rb
=> fix: fix RuleBuilder issue (#955)

lib/mihari/structs/censys.rb, spec/concerns/retriable_spec.rb, spec/http_spec.rb
=> fix: fix Censys AS key issue (#1136)
